name: Spell Checking


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  codespell:
    name: Analyze spelling with codespell
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [python]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          languages: ${{ matrix.language }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell
  misspell:
    name: Check spelling with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Misspell
        run: ./misspell -error
